[package]
name = "monitor-write"
version = "0.1.0"
authors = ["Hendrik <dev.nipe.systems@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.12"
inotify = "0.8"
signal-hook = "0.1.15"
